---
---
---I wrote this in game while testing, it's surprisingly functional, but very simple
---
--- This selects the second slot, which should have fuel, and then refuels
turtle.select(2)
turtle.refuel()
---This initializes a variable for a repeat block, and then starts the repeat block
x = 128
repeat
    --- This digs a 3 tall column
    turtle.dig()
    turtle.forward()
    turtle.digUp()
    turtle.digDown()
    --- It then selects the final slot, and checks if it has anything in it
    turtle.select(16)
    if turtle.getItemCount() > 0 then
        --- If it has something in it, the turtle will place a remote access storage chest, in slot 1, below it
        turtle.select(1)
        turtle.placeDown()
        --- It will then recurse through it's inventory, placing everything inside into the chest
        a = 16
        repeat
            turtle.select(a)
            turtle.dropDown()
            a = a - 1
        until a == 1
        ---This ensures the first slot is selected in case of server lag, then picks the chest back up, and selects the final slot
        turtle.select(1)
        turtle.digDown()
        turtle.select(16)
    end
    --- It then selects the first slot again, so mined items enter the inventory from the beginning, and lowers the repeat variable
    turtle.select(1)
    x = x - 1
until x == 0
---
---
--- This program will simply mine a 128 (or whatever variable x is initialized to) long 3 tall 1 wide tunnel
--- It will place a chest (which should be some kind of remote access inventory so it's automatically emptied elsewhere)
--- And put the items inside it into the chest if it gets full. this way it wont drop items
---
--- It is a simple script, no functions or anything, it also has no error handling
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 16/05/2021 11:20
---