---
---
--- A variant of torch that is made to put torches through a strip mine
--- Should be used after it's strip-mined
---

--- First declare variables
strips = 0 --- number of strips
stripLength = 32 --- Length of strips
direction = 0 --- Which direction relative to where the turtle is facing do you want it to progress,
--- left = 0, right = 1

--- Now for the functions

function turn()
    if direction == 0 then
        turtle.turnLeft()
        dig(3)
        turtle.turnLeft()
        direction = 1
    elseif direction == 1 then
        turtle.turnRight()
        dig(3)
        turtle.turnRight()
        direction = 0
    end
end


---
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 21/05/2021 17:20
---