---
--- This will be an advanced implementation of Strip3 made in my IDE rather than in-game
---
---

--- First declare variables
maxStrips = 0 --- Maximum number of strips, should be multiple of 2 for efficiency, 0 for unlimited
stripLength = 32 --- Length of strips, 32 default, don't go too high or chunks may not be loaded



---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 17/05/2021 13:42
---