---
--- A program meant to fetch and if needed update my various programs automatically, so I don't have to pastebin get everything all the fucking time
---




---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonat.
--- DateTime: 07/06/2021 09:43
---