---
--- A program I made in-game while testing
---
---
--- Refuel and set variable
turtle.select(2)
turtle.refuel()
x = 20 --- How many torches to place
turtle.select(1)
--- Repeat block for placing torches
repeat
    --- Variable for spaces to move
    a = 6
    --- Repeat block for moving
    repeat
        --- Moves forward, checks if something is in front of it
        turtle.forward()
        --- If something is in front, it waits for 10 seconds and checks again
        if turtle.detect() then
            sleep(10)
            --- If something is still in front, it sends an error and exits the program
            if turtle.detect() then
                error("I got stuck :(")
                exit()
            end
        end
        --- decrement the movement counter
        a = a -1
    until a == 0
    --- Turns around, places torch, then turns around again
    turtle.turnLeft()
    turtle.turnLeft()
    turtle.place()
    turtle.turnLeft()
    turtle.turnLeft()
    --- Decrements the torch counter
    x = x - 1
until x == 0
---
---
---
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 18/05/2021 12:18
---