---
---
--- A variant of torch that is made to put torches around a tunnel
--- Should be used after it's strip-mined, and strip-torched
---


--- First the variables
tunnelLength = 128 --- The length of the tunnel
tunnelWidth = 5 --- The width of the tunnel
direction = 1 --- Which direction relative to where the turtle is facing do you want it to progress, left = 0, right = 1

--- Then the functions

--- This checks if something is in front of it and then moves
function move()
    --- If something is in front, it waits for 10 seconds and checks again
    if turtle.detect() then
        sleep(10)
        --- If something is still in front, it sends an error and exits the program
        if turtle.detect() then
            error("I got stuck :(")
            exit()
        end
        --- If there isn't anything in front it moves
    else
        turtle.forward()
    end
end

function placeTorch()
    --- Turns around, places torch, then turns around again
    turtle.turnLeft()
    turtle.turnLeft()
    turtle.place()
    turtle.turnLeft()
    turtle.turnLeft()
end



---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 19/05/2021 12:29
---