---
--- A variant of StripMine meant to dig a big main tunnel for the mine
---

--- First the variables
tunnelLength = 128 --- The length of the tunnel
tunnelWidth = 5 --- The width of the tunnel
direction = 1 --- Which direction relative to where the turtle is facing do you want it to progress,
--- left = 0, right = 1


--- Then I define the functions, starting with deposit, these are mostly the same as with StripMine
function deposit ()
    --- It makes sure slot 1 is selected, which should hold the remote chest, and then places it below itself
    turtle.select(1)
    turtle.placeDown()
    --- It then sets the variable for the repeat block to go through the inventory
    local a = 16
    repeat
        --- It selects the next slot, and puts the items into the chest below
        turtle.select(a)
        turtle.dropDown()
        a = a -1
    until a == 1
    --- Finally it makes sure the first slot is selected, and picks the chest back up
    turtle.select(1)
    turtle.digDown()
end

--- Then I define the dig function
function dig (length)
    --- A repeat block that will go for the length of the parameter variable
    repeat
        --- First it digs in front of itself, then moves into the hole it dug and digs above and below
        turtle.dig()
        --- This is to stop gravel from breaking things
        while turtle.detect() do
            turtle.dig()
        end
        turtle.forward()
        turtle.digUp()
        turtle.digDown()
        --- Then it checks if it's inventory is full or not
        if turtle.getItemCount(16) > 0 then
            --- If it is full then it deposits it's items
            deposit()
        end
        --- Finally it makes sure the first slot is selected, and  decrements the length count by 1
        turtle.select(1)
        length = length - 1
    until length == 0
end

function turn()
    if direction == 0 then
        turtle.turnLeft()
        dig(1)
        turtle.turnLeft()
        direction = 1
    elseif direction == 1 then
        turtle.turnRight()
        dig(1)
        turtle.turnRight()
        direction = 0
    end
end

--- Now for the strip function (ooo, saucy)
function tunnel ()

    --- Get the maximum width  based on fuel
    local a = turtle.getFuelLevel()
    fuelWidth = math.floor(a / (tunnelLength * 1.1))
    --- Set the maxStrips to the lowest of either maxStrips or fuelStrips
    if fuelWidth < tunnelWidth then
        error("Not enough fuel for this tunnel")
        exit()
    end

    --- Start strip mining
    local strips = tunnelWidth
    repeat
        --- Digs the strip, turns and moves 3 blocks, then digs back
        dig(tunnelLength)
        strips = strips - 1
        --- If there is another strip to dig, it loops back
        if strips ~= 0 then
            turn()
            dig(tunnelLength)
            --- decrements the strips by 1
            strips = strips - 1
        end
        --- If there are more strips to dig, it moves to where the next one will start
        if strips ~= 0 then
            turn()
        end
    until strips == 0
    --- Once it's finished digging it performs one last deposit
    deposit()
end

--- Now the actual code

---Refuels
turtle.select(2)
turtle.refuel()
turtle.select(1)
--- Tunnels
tunnel()

--- If the width is uneven, it turns around and comes back
if tunnelWidth % 2 == 1 then
    turtle.turnLeft()
    turtle.turnLeft()
    dig(tunnelLength)
end

---
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 18/05/2021 12:28
---