---
--- A program to harvest wood automatically
---


--- Function to deposit the items
function deposit ()
    --- It makes sure slot 1 is selected, which should hold the remote chest, and then places it below itself
    --- It also makes sure the space above it is clear
    turtle.digUp()
    turtle.select(1)
    turtle.placeUp()
    --- It then sets the variable for the repeat block to go through the inventory
    a = 16
    repeat
        --- It selects the next slot, and puts the items into the chest below
        turtle.select(a)
        turtle.dropUp()
        a = a - 1
    until a == 2
    --- Finally it makes sure the first slot is selected, and picks the chest back up
    turtle.select(1)
    turtle.digUp()
end

--- Function to check for wood
function waitForWood ()
    local waiting = true

    while waiting do
        --- inspect block in front
        local isBlock, blockData = turtle.inspect()
        --- If there is not block, then plant saplings
        if not isBlock then
            plant()
        else
            --- If there is a block, see if it's wood
            --- If it is wood, then chop
            if blockData.name == "minecraft:spruce_log" then
                chop()
            end
        end
        --- After checking and before checking again, wait for 20 seconds to prevent server lag
    end
end

--- Function to chop the tree
function chop ()

end

--- Function to replenish saplings
function plant ()

end

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jonathan.
--- DateTime: 08/06/2021 09:17
---